version: "2.2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - node.name=nodo1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet

  apm:
    image: docker.elastic.co/apm/apm-server:6.5.4
    ports:
      - "8200:8200"
    environment:
        SERVER_NAME: localhost
        ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - "5601:5601"
    environment:
        SERVER_NAME: localhost
        ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch

  djangoapp:
    build: ./pycon2019-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pycon2019-app/myproject:/myproject
    ports:
      - "8000:8000"
    networks:
      - esnet

networks:
  esnet:
